### ISSUE TITLE
出现了奇怪的报错

### ISSUE THREAD

**Issue by yiliya123** [Encinet/Aliwaka#3]
[00:52:09 ERROR]: Thread Aliwaka-Guard failed main thread check: chunk unload
java.lang.Throwable: null
        at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at org.bukkit.craftbukkit.v1_18_R2.CraftWorld.unloadChunk0(CraftWorld.java:414) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at org.bukkit.craftbukkit.v1_18_R2.CraftWorld.unloadChunk(CraftWorld.java:400) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at org.bukkit.craftbukkit.v1_18_R2.CraftWorld.unloadChunk(CraftWorld.java:395) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at org.bukkit.craftbukkit.v1_18_R2.CraftChunk.unload(CraftChunk.java:203) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at com.obcbo.aliwaka.function.Guard.chunk(Guard.java:122) ~[Aliwaka-1.2.3-SNAPSHOT.jar:?]
        at com.obcbo.aliwaka.function.Guard.tpscheck(Guard.java:103) ~[Aliwaka-1.2.3-SNAPSHOT.jar:?]
        at com.obcbo.aliwaka.function.Guard.core(Guard.java:59) ~[Aliwaka-1.2.3-SNAPSHOT.jar:?]
        at com.obcbo.aliwaka.function.Guard.run(Guard.java:46) ~[Aliwaka-1.2.3-SNAPSHOT.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[00:52:09 WARN]: [Aliwaka] Guard OFF

**Comment by noctiro** [comment]
上学中（没空），寒假回来继续更新
